services:
  - type: web
    name: my-app
    env: node # Specifies Node.js as the environment
    plan: free # Free plan for low traffic or development use
    buildCommand: "npm install --production && npm run build" # Command to install dependencies
    startCommand: "npm run preview" # Command to start your app (adjust if needed)
    branch: main # The branch to deploy from
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://username:password@cluster.mongodb.net/databaseName?retryWrites=true&w=majority" # Replace with your actual MongoDB URI

# If you're using a managed database (e.g., MongoDB):
databases:
  - name: my-mongo-db # Name of your MongoDB database
    plan: free # Free tier plan for development
